// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var STOREFRONT_URL = "https://madeiraoriginals-cve6q.myshopify.com/api/2025-07/graphql.json";
var STOREFRONT_TOKEN = "bbcc49de92200adcd5c43d7f6f847485";
var QUERY = (
  /* GraphQL */
  `
  query SearchProducts($query: String, $first: Int!) {
    products(first: $first, query: $query) {
      edges {
        node {
          id
          title
          handle
          productType
          tags
          description
          priceRange { minVariantPrice { amount currencyCode } }
          images(first: 1) { edges { node { url altText } } }
          onlineStoreUrl
        }
      }
    }
  }
`
);
var search_products_default = defineTool({
  name: "search_products",
  title: "Search products",
  description: "Search Madeira Originals products (t-shirts, hoodies, prints, accessories) from the live Shopify catalog. Returns title, handle, price, image, and product URL.",
  inputSchema: {
    query: z.string().optional().describe(
      "Shopify search query, e.g. 'levada', 'tag:streetwear', 'product_type:hoodie'. Leave empty to list latest products."
    ),
    limit: z.number().int().min(1).max(50).optional().describe("Max results (default 12).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const res = await fetch(STOREFRONT_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-Shopify-Storefront-Access-Token": STOREFRONT_TOKEN
      },
      body: JSON.stringify({ query: QUERY, variables: { query: query ?? "", first: limit ?? 12 } })
    });
    if (!res.ok) {
      return { content: [{ type: "text", text: `Shopify error ${res.status}` }], isError: true };
    }
    const json = await res.json();
    const products = (json.data?.products?.edges ?? []).map((e) => ({
      title: e.node.title,
      handle: e.node.handle,
      productType: e.node.productType,
      tags: e.node.tags,
      price: `${e.node.priceRange.minVariantPrice.amount} ${e.node.priceRange.minVariantPrice.currencyCode}`,
      image: e.node.images.edges[0]?.node?.url ?? null,
      url: `https://madeiraoriginals.pt/products/${e.node.handle}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(products, null, 2) }],
      structuredContent: { products }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var STOREFRONT_URL2 = "https://madeiraoriginals-cve6q.myshopify.com/api/2025-07/graphql.json";
var STOREFRONT_TOKEN2 = "bbcc49de92200adcd5c43d7f6f847485";
var QUERY2 = (
  /* GraphQL */
  `
  query GetProduct($handle: String!) {
    product(handle: $handle) {
      id
      title
      handle
      description
      productType
      tags
      priceRange { minVariantPrice { amount currencyCode } }
      images(first: 10) { edges { node { url altText } } }
      variants(first: 25) {
        edges {
          node {
            id
            title
            availableForSale
            price { amount currencyCode }
            selectedOptions { name value }
          }
        }
      }
    }
  }
`
);
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product",
  description: "Fetch a single Madeira Originals product by its handle, including full description, variants, and images.",
  inputSchema: {
    handle: z2.string().min(1).describe("Product handle, e.g. 'levada-walks-madeira-island-t-shirt'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ handle }) => {
    const res = await fetch(STOREFRONT_URL2, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-Shopify-Storefront-Access-Token": STOREFRONT_TOKEN2
      },
      body: JSON.stringify({ query: QUERY2, variables: { handle } })
    });
    if (!res.ok) {
      return { content: [{ type: "text", text: `Shopify error ${res.status}` }], isError: true };
    }
    const json = await res.json();
    const p = json.data?.product;
    if (!p) {
      return { content: [{ type: "text", text: `Product not found: ${handle}` }], isError: true };
    }
    const product = {
      title: p.title,
      handle: p.handle,
      description: p.description,
      productType: p.productType,
      tags: p.tags,
      priceFrom: `${p.priceRange.minVariantPrice.amount} ${p.priceRange.minVariantPrice.currencyCode}`,
      images: p.images.edges.map((e) => e.node.url),
      variants: p.variants.edges.map((e) => ({
        title: e.node.title,
        available: e.node.availableForSale,
        price: `${e.node.price.amount} ${e.node.price.currencyCode}`,
        options: e.node.selectedOptions
      })),
      url: `https://madeiraoriginals.pt/product/${p.handle}`
    };
    return {
      content: [{ type: "text", text: JSON.stringify(product, null, 2) }],
      structuredContent: { product }
    };
  }
});

// src/lib/mcp/tools/list-journal-posts.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var SUPABASE_URL = "https://hkyypgqbiwaxpyiflzhl.supabase.co";
var SUPABASE_ANON = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhreXlwZ3FiaXdheHB5aWZsemhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgxODAxNTgsImV4cCI6MjA5Mzc1NjE1OH0.PGyIx9auFlwtQUSyiXqV26AtMYdXdEoWWyoxcFysueg";
var list_journal_posts_default = defineTool3({
  name: "list_journal_posts",
  title: "List journal posts",
  description: "List published Madeira Originals journal articles (title, slug, excerpt, tags, published date).",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).optional().describe("Max results (default 20)."),
    tag: z3.string().optional().describe("Filter by tag (exact match).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, tag }) => {
    const params = new URLSearchParams({
      select: "slug,title,excerpt,tags,published_at,cover_url",
      published: "eq.true",
      order: "published_at.desc.nullslast",
      limit: String(limit ?? 20)
    });
    if (tag) params.set("tags", `cs.{${tag}}`);
    const res = await fetch(`${SUPABASE_URL}/rest/v1/articles?${params}`, {
      headers: { apikey: SUPABASE_ANON, Authorization: `Bearer ${SUPABASE_ANON}` }
    });
    if (!res.ok) {
      return { content: [{ type: "text", text: `Error ${res.status}: ${await res.text()}` }], isError: true };
    }
    const rows = await res.json();
    const posts = rows.map((r) => ({
      ...r,
      url: `https://madeiraoriginals.pt/journal/${r.slug}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(posts, null, 2) }],
      structuredContent: { posts }
    };
  }
});

// src/lib/mcp/tools/get-journal-post.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4.4.3";
var SUPABASE_URL2 = "https://hkyypgqbiwaxpyiflzhl.supabase.co";
var SUPABASE_ANON2 = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhreXlwZ3FiaXdheHB5aWZsemhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgxODAxNTgsImV4cCI6MjA5Mzc1NjE1OH0.PGyIx9auFlwtQUSyiXqV26AtMYdXdEoWWyoxcFysueg";
var get_journal_post_default = defineTool4({
  name: "get_journal_post",
  title: "Get journal post",
  description: "Fetch the full body of a published Madeira Originals journal article by slug (English + Portuguese if present).",
  inputSchema: {
    slug: z4.string().min(1).describe("Article slug.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const params = new URLSearchParams({
      select: "slug,title,title_pt,excerpt,excerpt_pt,body_md,body_md_pt,tags,published_at,cover_url",
      slug: `eq.${slug}`,
      published: "eq.true",
      limit: "1"
    });
    const res = await fetch(`${SUPABASE_URL2}/rest/v1/articles?${params}`, {
      headers: { apikey: SUPABASE_ANON2, Authorization: `Bearer ${SUPABASE_ANON2}` }
    });
    if (!res.ok) {
      return { content: [{ type: "text", text: `Error ${res.status}` }], isError: true };
    }
    const rows = await res.json();
    if (!rows.length) {
      return { content: [{ type: "text", text: `Post not found: ${slug}` }], isError: true };
    }
    const post = { ...rows[0], url: `https://madeiraoriginals.pt/journal/${rows[0].slug}` };
    return {
      content: [{ type: "text", text: JSON.stringify(post, null, 2) }],
      structuredContent: { post }
    };
  }
});

// src/lib/mcp/tools/subscribe-newsletter.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^4.4.3";
var SUPABASE_URL3 = "https://hkyypgqbiwaxpyiflzhl.supabase.co";
var SUPABASE_ANON3 = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhreXlwZ3FiaXdheHB5aWZsemhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgxODAxNTgsImV4cCI6MjA5Mzc1NjE1OH0.PGyIx9auFlwtQUSyiXqV26AtMYdXdEoWWyoxcFysueg";
var subscribe_newsletter_default = defineTool5({
  name: "subscribe_newsletter",
  title: "Subscribe to newsletter",
  description: "Subscribe an email address to the Madeira Originals newsletter.",
  inputSchema: {
    email: z5.string().email().describe("Subscriber email address."),
    source: z5.string().optional().describe("Where the subscription originated (default: 'mcp').")
  },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ email, source }) => {
    const res = await fetch(`${SUPABASE_URL3}/rest/v1/newsletter_subscribers`, {
      method: "POST",
      headers: {
        apikey: SUPABASE_ANON3,
        Authorization: `Bearer ${SUPABASE_ANON3}`,
        "Content-Type": "application/json",
        Prefer: "return=minimal,resolution=ignore-duplicates"
      },
      body: JSON.stringify({ email, source: source ?? "mcp" })
    });
    if (!res.ok) {
      const t = await res.text();
      return { content: [{ type: "text", text: `Subscribe failed ${res.status}: ${t}` }], isError: true };
    }
    return { content: [{ type: "text", text: `Subscribed ${email}.` }] };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "madeira-originals-mcp",
  title: "Madeira Originals",
  version: "0.1.0",
  instructions: "Tools for Madeira Originals \u2014 a premium Madeiran Atlantic lifestyle brand. Use `search_products` and `get_product` to browse the Shopify catalog (t-shirts, hoodies, Island of Flowers prints, accessories). Use `list_journal_posts` and `get_journal_post` for editorial articles. Use `subscribe_newsletter` to add an email to the mailing list.",
  tools: [search_products_default, get_product_default, list_journal_posts_default, get_journal_post_default, subscribe_newsletter_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
